version: "3"

services:
  server:
    container_name: 'cookie-cloudflare'
    image: ${DOCKER_IMAGE:-caomeiyouren/cookie-cloudflare}
    # build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: "Asia/Shanghai"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
